SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Player
PLAYER_RADIUS = 20
LINE_WIDTH = 2

# Player Movement
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

# Asteroids
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Combat
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

# Colors
PLAYER_COLOR = (0, 255, 115)
SHOT_COLOR = (0, 255, 80)
ASTEROID_COLOR = (0, 200, 70)
BACKGROUND_COLOR = (0, 10, 2)

